// var testimonials = [
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial157.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial44.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial163.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial172.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial134.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial113.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial161.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial168.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial186.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial143.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial154.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial145.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial174.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial197.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial152.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial176.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial140.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial178.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial133.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial175.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial151.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial137.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial181.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial184.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial158.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial155.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial159.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial139.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial58.jpg',
// 	'https://static.beepi.com/images/Testimonials/LoveStories/testimonial171.jpg'
// ];

// var ogPhotos = [
// 	'20150309_155747.jpg',
// 	'20150311_121811.jpg',
// 	'20150311_172446.jpg',
// 	'20150317_152049-1.jpg',
// 	'20150318_174028.jpg',
// 	'B Panamera 2.JPG',
// 	'Davids prius .JPG',
// 	'DSC_0001.JPG',
// 	'Eric Edge 3.JPG',
// 	'FullSizeRender 2.jpg',
// 	'FullSizeRender 3.jpg',
// 	'FullSizeRender 4.jpg',
// 	'FullSizeRender 5.jpg',
// 	'FullSizeRender 6.jpg',
// 	'FullSizeRender 7.jpg',
// 	'FullSizeRender 8.jpg',
// 	'FullSizeRender 9.jpg',
// 	'FullSizeRender 10.jpg',
// 	'FullSizeRender 11.jpg',
// 	'FullSizeRender 12.jpg',
// 	'FullSizeRender 13.jpg',
// 	'FullSizeRender 14.jpg',
// 	'FullSizeRender 15.jpg',
// 	'FullSizeRender 16.jpg',
// 	'FullSizeRender 17.jpg',
// 	'FullSizeRender 18.jpg',
// 	'FullSizeRender 19.jpg',
// 	'FullSizeRender 20.jpg',
// 	'FullSizeRender 21.jpg',
// 	'FullSizeRender 22.jpg',
// 	'FullSizeRender 23.jpg',
// 	'FullSizeRender 24.jpg',
// 	'FullSizeRender 25.jpg',
// 	'FullSizeRender 26.jpg',
// 	'FullSizeRender 27.jpg',
// 	'FullSizeRender 28.jpg',
// 	'FullSizeRender 29.jpg',
// 	'FullSizeRender 30.jpg',
// 	'FullSizeRender.jpg',
// 	'IMAG1431.jpg',
// 	'IMAG1470.jpg',
// 	'IMAG1505.jpg',
// 	'IMAG1524.jpg',
// 	'IMAG1531.jpg',
// 	'IMAG1541.jpg',
// 	'IMAG1557.jpg',
// 	'IMAG1877.jpg',
// 	'IMAG1941.jpg',
// 	'IMAG1955.jpg',
// 	'IMAG1974.jpg',
// 	'IMAG1979.jpg',
// 	'IMAG2053.jpg',
// 	'IMAG2076.jpg',
// 	'IMAG2101.jpg',
// 	'IMAG2114.jpg',
// 	'IMAG2143.jpg',
// 	'IMAG2187.jpg',
// 	'IMAG2400.jpg',
// 	'IMAG2443.jpg',
// 	'IMAG2508.jpg',
// 	'IMAG2571.jpg',
// 	'IMAG2615.jpg',
// 	'IMAG2706.jpg',
// 	'IMAG2717.jpg',
// 	'IMAG2849.jpg',
// 	'IMAG2955.jpg',
// 	'IMAG2980.jpg',
// 	'IMAG3004.jpg',
// 	'IMAG3048.jpg',
// 	'IMAG3137.jpg',
// 	'IMAG3160.jpg',
// 	'IMAG3239.jpg',
// 	'IMAG3277.jpg',
// 	'IMAG3319.jpg',
// 	'IMAG3358.jpg',
// 	'IMAG3397.jpg',
// 	'IMAG3402.jpg',
// 	'IMAG3442.jpg',
// 	'IMAG3595.jpg',
// 	'IMAG3632.jpg',
// 	'IMAG3730.jpg',
// 	'IMAG3848.jpg',
// 	'IMAG3868.jpg',
// 	'IMAG3880.jpg',
// 	'IMAG4007.jpg',
// 	'image 2.jpg',
// 	'image 3.jpg',
// 	'image 4.jpg',
// 	'image 5.jpg',
// 	'image 6.jpg',
// 	'image.jpg',
// 	'image1 2.JPG',
// 	'image1 3.JPG',
// 	'image1.JPG',
// 	'IMG_0322.JPG',
// 	'IMG_1105.JPG',
// 	'IMG_1279.JPG',
// 	'IMG_1319.JPG',
// 	'IMG_1328.JPG',
// 	'IMG_1377.JPG',
// 	'IMG_1386.JPG',
// 	'IMG_1447.JPG',
// 	'IMG_1468.JPG',
// 	'IMG_1521.JPG',
// 	'IMG_1580.JPG',
// 	'IMG_20140527_194225.jpg',
// 	'IMG_20150302_173321.jpg',
// 	'IMG_20150306_151119.jpg',
// 	'IMG_20150319_185711~2.jpg',
// 	'IMG_20150320_165040.jpg',
// 	'IMG_20150321_094518.jpg',
// 	'IMG_20150321_134215.jpg',
// 	'IMG_20150323_102815~2.jpg',
// 	'IMG_20150323_163733.jpg',
// 	'IMG_20150324_123538.jpg',
// 	'IMG_20150324_201630.jpg',
// 	'IMG_20150325_101308~2.jpg',
// 	'IMG_20150326_154203.jpg',
// 	'IMG_20150327_131836.jpg',
// 	'IMG_20150328_102131.jpg',
// 	'IMG_20150328_135053.jpg',
// 	'IMG_20150330_143808.jpg',
// 	'IMG_20150331_105946~2.jpg',
// 	'IMG_20150331_113648.jpg',
// 	'IMG_20150402_202426.jpg',
// 	'IMG_20150403_092541.jpg',
// 	'IMG_20150403_095521~2.jpg',
// 	'IMG_20150404_093037~2.jpg',
// 	'IMG_20150404_140934.jpg',
// 	'IMG_20150406_191315.jpg',
// 	'IMG_20150407_094843.jpg',
// 	'IMG_20150407_140251.jpg',
// 	'IMG_20150407_184527.jpg',
// 	'IMG_20150408_160423~2.jpg',
// 	'IMG_20150408_191258.jpg',
// 	'IMG_20150409_112412.jpg',
// 	'IMG_20150409_150517~2.jpg',
// 	'IMG_20150410_114051.jpg',
// 	'IMG_20150410_132928.jpg',
// 	'IMG_20150410_160729~2.jpg',
// 	'IMG_20150413_143825~2.jpg',
// 	'IMG_20150413_185436~2.jpg',
// 	'IMG_20150413_190906~2.jpg',
// 	'IMG_20150414_133358~2.jpg',
// 	'IMG_20150416_184151.jpg',
// 	'IMG_20150416_191015.jpg',
// 	'IMG_20150418_094520.jpg',
// 	'IMG_20150418_141043.jpg',
// 	'IMG_20150421_103515~2.jpg',
// 	'IMG_20150421_193933~2.jpg',
// 	'IMG_20150422_143931.jpg',
// 	'IMG_20150422_183813~2.jpg',
// 	'IMG_20150423_105147.jpg',
// 	'IMG_20150423_161703~2.jpg',
// 	'IMG_20150424_101543~2.jpg',
// 	'IMG_20150424_134554.jpg',
// 	'IMG_20150424_163100~3.jpg',
// 	'IMG_20150428_152521.jpg',
// 	'IMG_20150429_095722~2~2.jpg',
// 	'IMG_20150429_193322~2.jpg',
// 	'IMG_20150430_181502.jpg',
// 	'IMG_20150430_190712.jpg',
// 	'IMG_20150505_181338~2.jpg',
// 	'IMG_20150505_183032.jpg',
// 	'IMG_20150506_131637.jpg',
// 	'IMG_20150507_123550~2.jpg',
// 	'IMG_20150507_140419.jpg',
// 	'IMG_20150512_100213.jpg',
// 	'IMG_20150512_101529~2.jpg',
// 	'IMG_20150512_140848.jpg',
// 	'IMG_20150513_130203~2.jpg',
// 	'IMG_20150513_155201.jpg',
// 	'IMG_20150513_203101~2.jpg',
// 	'IMG_20150514_114131~2.jpg',
// 	'IMG_20150514_134410.jpg',
// 	'IMG_20150515_091547.jpg',
// 	'IMG_20150515_134321.jpg',
// 	'IMG_20150518_181039~2.jpg',
// 	'IMG_20150519_193831.jpg',
// 	'IMG_20150520_165144.jpg',
// 	'IMG_20150521_154704.jpg',
// 	'IMG_20150525_184519.jpg',
// 	'IMG_20150529_183020.jpg',
// 	'IMG_20150530_191515.jpg',
// 	'IMG_20150603_103359.jpg',
// 	'Lawrence.jpeg'
// ];

function createOGPhoto (index, type, photo) {
	$('ul').append(
		'<li id="' + type + '_' + index +
			'" data-customer-type="original" ' + 
			'onclick="view(\'#' + type + '_'+ index + '\', \'Early Bird\')" ' + 
			'style="background-image:url(' + photo + ');">' + 
			'<div class="details">' +
				'<span class="name">Early Bird</span>' +
			'</div>' + 
		'</li>'
	);
};
function OGHeadAppend (tempImage, photo) {
	var height = tempImage.height;
	var width = tempImage.width;

	$('head').append(
		'<!-- Facebook Open Graph Tags -->' +
		'<meta property="og:type" content="website">' +
		'<meta property="og:title" content="Beepi | Capturing The Moment | Early Bird">' +
		'<meta name="twitter:description" content="An OG Beepi Customer">' +
		'<meta property="og:image" content="'+photo+'">' + 
		'<meta property="og:image:width" content="'+ width + '">' +
		'<meta property="og:image:height" content="' + height + '">' + 

		'<!-- Twitter Card Tags -->' + 
		'<meta name="twitter:card" content="summary_large_image">' +
		'<meta name="twitter:site" content="@beepi">' +
		'<meta name="twitter:title" content="Beepi | Capturing The Moment | Early Bird">' +
		'<meta name="twitter:description" content="An OG Beepi Customer">' +
		'<meta name="twitter:image" content="' + photo + '">'
	);
};
function OGMetadata (photo) {
	var tmpImg = new Image();
	tmpImg.src = photo;
	$(tmpImg).on('load',function() {
		OGHeadAppend(tmpImg,photo);
	});
};

var startOriginals = 0;

function getOriginals(interval) {
	
	var endOriginals = startOriginals + interval;

	// var endTestimonials = endOriginals;
	// if (endTestimonials > testimonials.length) {
	// 	endTestimonials = testimonials.length;
	// };

	var endOGPhotos = endOriginals;
	if (endOGPhotos > ogPhotos.length) {
		endOGPhotos = ogPhotos.length;
	};

	for (i = startOriginals; i < endOGPhotos; i++) {
		// var ogPhoto = 'images/capturingTheMomentPhotos/' + ogPhotos[i].split(' ').join('%20');
		// createOGPhoto(i,'og',ogPhoto);
		createOGPhoto(i,'og',ogPhotos[i]);
	};

	// for (i = startOriginals; i < endTestimonials; i++) {
	// 	var testimonialPhoto = testimonials[i];
	// 	createOGPhoto(i,'testimonial',testimonialPhoto);
	// };

	startOriginals = endOriginals + 1;
};

var ogPhotos = [
	'http://i.imgur.com/u1jEALD.jpg',
	'http://i.imgur.com/cpy7mIE.jpg',
	'http://i.imgur.com/pnZD6X0.jpg',
	'http://i.imgur.com/T81YY17.jpg',
	'http://i.imgur.com/Ry2SP1U.jpg',
	'http://i.imgur.com/mCXJsvv.jpg',
	'http://i.imgur.com/cwT5nOv.jpg',
	'http://i.imgur.com/G8lVIaB.jpg',
	'http://i.imgur.com/bDk4YGS.jpg',
	'http://i.imgur.com/YleSzAw.jpg',
	'http://i.imgur.com/obGOfyg.jpg',
	'http://i.imgur.com/1w1Nwsd.jpg',
	'http://i.imgur.com/oEZ51D6.jpg',
	'http://i.imgur.com/sMXsXGM.jpg',
	'http://i.imgur.com/s3TTxno.jpg',
	'http://i.imgur.com/mErqZRI.jpg',
	'http://i.imgur.com/2NtYVOo.jpg',
	'http://i.imgur.com/FUipZdS.jpg',
	'http://i.imgur.com/OL689Qh.jpg',
	'http://i.imgur.com/3HLDYgn.jpg',
	'http://i.imgur.com/y55wp1g.jpg',
	'http://i.imgur.com/gEmUEnl.jpg',
	'http://i.imgur.com/aRk9UO6.jpg',
	'http://i.imgur.com/kSmdXbk.jpg',
	'http://i.imgur.com/M4AzWDE.jpg',
	'http://i.imgur.com/rwSglh1.jpg',
	'http://i.imgur.com/6Q7qlW9.jpg',
	'http://i.imgur.com/1relyKc.jpg',
	'http://i.imgur.com/TPeyExe.jpg',
	'http://i.imgur.com/eNi72B5.jpg',
	'http://i.imgur.com/Usr8JCP.jpg',
	'http://i.imgur.com/YWzcpUe.jpg',
	'http://i.imgur.com/Ne6VaeD.jpg',
	'http://i.imgur.com/gn7aCt4.jpg',
	'http://i.imgur.com/TvwEOjc.jpg',
	'http://i.imgur.com/4j0zwO4.jpg',
	'http://i.imgur.com/4YjVWlS.jpg',
	'http://i.imgur.com/IfdYyOJ.jpg',
	'http://i.imgur.com/UvmYAWU.jpg',
	'http://i.imgur.com/nbi4PF7.jpg',
	'http://i.imgur.com/7xgiatl.jpg',
	'http://i.imgur.com/5TpByQi.jpg',
	'http://i.imgur.com/9RD0pHz.jpg',
	'http://i.imgur.com/vrgXuq4.jpg',
	'http://i.imgur.com/4e31FYD.jpg',
	'http://i.imgur.com/RYUlO9Q.jpg',
	'http://i.imgur.com/MCcuazh.jpg',
	'http://i.imgur.com/k8HTlnx.jpg',
	'http://i.imgur.com/NVnw0Rg.jpg',
	'http://i.imgur.com/1QOlYyj.jpg',
	'http://i.imgur.com/p3lIW12.jpg',
	'http://i.imgur.com/EXVU4bL.jpg',
	'http://i.imgur.com/lutK9gJ.jpg',
	'http://i.imgur.com/qOffV86.jpg',
	'http://i.imgur.com/qmhx5eR.jpg',
	'http://i.imgur.com/uddfC1b.jpg',
	'http://i.imgur.com/GObbE7g.jpg',
	'http://i.imgur.com/JPoJwzQ.jpg',
	'http://i.imgur.com/GIA1wCG.jpg',
	'http://i.imgur.com/omnJoeT.jpg',
	'http://i.imgur.com/1GQ4FY7.jpg',
	'http://i.imgur.com/SlbeT4K.jpg',
	'http://i.imgur.com/M9Z5ubI.jpg',
	'http://i.imgur.com/q1gWKqO.jpg',
	'http://i.imgur.com/IMyiMva.jpg',
	'http://i.imgur.com/NEiYESE.jpg',
	'http://i.imgur.com/IJrjZ9p.jpg',
	'http://i.imgur.com/6QjQddB.jpg',
	'http://i.imgur.com/VHl6bdS.jpg',
	'http://i.imgur.com/Uzeme1E.jpg',
	'http://i.imgur.com/13Eei9l.jpg',
	'http://i.imgur.com/K5cJkEd.jpg',
	'http://i.imgur.com/e1kdRBg.jpg',
	'http://i.imgur.com/BPKL6gg.jpg',
	'http://i.imgur.com/8QVYW9t.jpg',
	'http://i.imgur.com/VjktFt8.jpg',
	'http://i.imgur.com/VJr0DQ3.jpg',
	'http://i.imgur.com/meXnQjF.jpg',
	'http://i.imgur.com/EniHDWn.jpg',
	'http://i.imgur.com/In1JnD5.jpg',
	'http://i.imgur.com/K43ZPTb.jpg',
	'http://i.imgur.com/NddmXPK.jpg',
	'http://i.imgur.com/1JQFxc4.jpg',
	'http://i.imgur.com/cg9CIwY.jpg',
	'http://i.imgur.com/PnVI6qx.jpg',
	'http://i.imgur.com/XsaUV85.jpg',
	'http://i.imgur.com/96IswJL.jpg',
	'http://i.imgur.com/2RqiM7k.jpg',
	'http://i.imgur.com/3eWXOKo.jpg',
	'http://i.imgur.com/lTCws9s.jpg',
	'http://i.imgur.com/nxqZCAm.jpg',
	'http://i.imgur.com/0BorB2K.jpg',
	'http://i.imgur.com/a3UTLPD.jpg',
	'http://i.imgur.com/BB7vjuO.jpg',
	'http://i.imgur.com/7AQE1og.jpg',
	'http://i.imgur.com/cZtg7LL.jpg',
	'http://i.imgur.com/ya4xWnd.jpg',
	'http://i.imgur.com/Ksn0RJ7.jpg',
	'http://i.imgur.com/zJh3dsm.jpg',
	'http://i.imgur.com/K6h4aI3.jpg',
	'http://i.imgur.com/ype3zPW.jpg',
	'http://i.imgur.com/aIpkZlk.jpg',
	'http://i.imgur.com/WDosl1K.jpg',
	'http://i.imgur.com/aA8Wxfq.jpg',
	'http://i.imgur.com/FsojDvy.jpg',
	'http://i.imgur.com/t0reN1T.jpg',
	'http://i.imgur.com/vwaiK6U.jpg',
	'http://i.imgur.com/854jAXr.jpg',
	'http://i.imgur.com/mzDJ6R2.jpg',
	'http://i.imgur.com/EbZZJyg.jpg',
	'http://i.imgur.com/ZSOV44x.jpg',
	'http://i.imgur.com/OmfCIB8.jpg',
	'http://i.imgur.com/ThodqNy.jpg',
	'http://i.imgur.com/fcDEKmn.jpg',
	'http://i.imgur.com/PXmhusL.jpg',
	'http://i.imgur.com/QSfvwpQ.jpg',
	'http://i.imgur.com/eG6KspZ.jpg',
	'http://i.imgur.com/QnQCxxx.jpg',
	'http://i.imgur.com/4uGf5L2.jpg',
	'http://i.imgur.com/GXnO904.jpg',
	'http://i.imgur.com/rQ0V3Lh.jpg',
	'http://i.imgur.com/bf8XnGK.jpg',
	'http://i.imgur.com/FtfEMQP.jpg',
	'http://i.imgur.com/4RTFEVM.jpg',
	'http://i.imgur.com/6lkBaqQ.jpg',
	'http://i.imgur.com/BhiEGcv.jpg',
	'http://i.imgur.com/7CiP6u6.jpg',
	'http://i.imgur.com/ITxL6lh.jpg',
	'http://i.imgur.com/EjaQh9X.jpg',
	'http://i.imgur.com/rXbbrRf.jpg',
	'http://i.imgur.com/BHAPx9F.jpg',
	'http://i.imgur.com/UcOENLV.jpg',
	'http://i.imgur.com/HbpRwGT.jpg',
	'http://i.imgur.com/1tDV41n.jpg',
	'http://i.imgur.com/P3SeIbI.jpg',
	'http://i.imgur.com/i5ARZzK.jpg',
	'http://i.imgur.com/LKtvlyi.jpg',
	'http://i.imgur.com/EpP8bMn.jpg',
	'http://i.imgur.com/5kR59GN.jpg',
	'http://i.imgur.com/lNnIGwE.jpg',
	'http://i.imgur.com/MjcvDzg.jpg',
	'http://i.imgur.com/xcrOI7V.jpg',
	'http://i.imgur.com/9b7Vyci.jpg',
	'http://i.imgur.com/oWIBkGU.jpg',
	'http://i.imgur.com/jTCeo7v.jpg',
	'http://i.imgur.com/oi8QELS.jpg',
	'http://i.imgur.com/L1xT7R7.jpg',
	'http://i.imgur.com/sG01fMC.jpg',
	'http://i.imgur.com/Y781LUx.jpg',
	'http://i.imgur.com/ItXt3Uw.jpg',
	'http://i.imgur.com/nIEv0kx.jpg',
	'http://i.imgur.com/U3ci2PD.jpg',
	'http://i.imgur.com/xlCHUNO.jpg',
	'http://i.imgur.com/Ngt1MK6.jpg',
	'http://i.imgur.com/EAlELQn.jpg',
	'http://i.imgur.com/D7Q1t4h.jpg',
	'http://i.imgur.com/x80UU6R.jpg',
	'http://i.imgur.com/n2d51PX.jpg',
	'http://i.imgur.com/CBeDnGD.jpg',
	'http://i.imgur.com/ftLUp2P.jpg',
	'http://i.imgur.com/MoxIF1x.jpg',
	'http://i.imgur.com/z3FNjCa.jpg',
	'http://i.imgur.com/RrsbIWx.jpg',
	'http://i.imgur.com/1dbew8x.jpg',
	'http://i.imgur.com/li0DreY.jpg',
	'http://i.imgur.com/mn1IRKw.jpg',
	'http://i.imgur.com/OLdmxro.jpg',
	'http://i.imgur.com/g5bsJ2L.jpg',
	'http://i.imgur.com/yF0P6Ui.jpg',
	'http://i.imgur.com/5iRoXfH.jpg',
	'http://i.imgur.com/xLDRZMy.jpg',
	'http://i.imgur.com/VnCkpB4.jpg',
	'http://i.imgur.com/3qf4LyD.jpg',
	'http://i.imgur.com/suRrrMH.jpg',
	'http://i.imgur.com/gD8gJsP.jpg',
	'http://i.imgur.com/43YIben.jpg',
	'http://i.imgur.com/zBdgEXu.jpg',
	'http://i.imgur.com/gq1qfEJ.jpg',
	'http://i.imgur.com/ODAaPwa.jpg',
	'http://i.imgur.com/O9jE4hn.jpg',
	'http://i.imgur.com/KW8HLRH.jpg',
	'http://i.imgur.com/V74PySP.jpg',
	'http://i.imgur.com/suPG6lr.jpg',
	'http://i.imgur.com/f9rfEmy.jpg',
	'http://i.imgur.com/NNmW5Sz.jpg',
	'http://i.imgur.com/lG6qShx.jpg',
	'http://i.imgur.com/cp5XLD6.jpg',
	'http://i.imgur.com/M1iCTvZ.jpg',
	'http://i.imgur.com/TsNBAEm.jpg',
	'http://i.imgur.com/spmfFC7.jpg',
	'http://i.imgur.com/6uQ30jK.jpg',
	'http://i.imgur.com/NmiI0O0.jpg',
	'http://i.imgur.com/6ClZTb0.jpg',
	'http://i.imgur.com/7tfis3D.jpg',
	'http://i.imgur.com/cFBEP7K.jpg',
	'http://i.imgur.com/LprWVPQ.jpg',
	'http://i.imgur.com/I0Wau93.jpg',
	'http://i.imgur.com/Teut2SD.jpg',
	'http://i.imgur.com/STXtvpg.jpg',
	'http://i.imgur.com/xp7PYE1.jpg',
	'http://i.imgur.com/gv8jaye.jpg',
	'http://i.imgur.com/5WDGZCe.jpg',
	'http://i.imgur.com/w8mjLPO.jpg',
	'http://i.imgur.com/HiSZ41A.jpg',
	'http://i.imgur.com/bKlpUsE.jpg',
	'http://i.imgur.com/hkBsteV.jpg',
	'http://i.imgur.com/qssyWfM.jpg',
	'http://i.imgur.com/Siai4lM.jpg',
	'http://i.imgur.com/nHWMLJA.jpg',
	'http://i.imgur.com/snOvNEN.jpg',
	'http://i.imgur.com/ROAhFJ1.jpg',
	'http://i.imgur.com/eUukGAG.jpg',
	'http://i.imgur.com/aWnDeWY.jpg',
	'http://i.imgur.com/ggyTQI3.jpg',
	'http://i.imgur.com/sq8qFoZ.jpg',
	'http://i.imgur.com/drAvYhR.jpg',
	'http://i.imgur.com/gstmIyc.jpg',
	'http://i.imgur.com/NBTBaPw.jpg',
	'http://i.imgur.com/8tkKidj.jpg',
	'http://i.imgur.com/AwqnC42.jpg',
	'http://i.imgur.com/4FhgIqF.jpg',
	'http://i.imgur.com/9HVCbTp.jpg',
	'http://i.imgur.com/f4o5xDX.jpg',
	'http://i.imgur.com/o6WZ9H4.jpg',
	'http://i.imgur.com/ufCRUOf.jpg',
	'http://i.imgur.com/OHNajSZ.jpg',
	'http://i.imgur.com/TyGUZjj.jpg',
	'http://i.imgur.com/jSMMNWM.jpg',
	'http://i.imgur.com/MThGch2.jpg',
	'http://i.imgur.com/ZratDwI.jpg',
	'http://i.imgur.com/Q9N9hwv.jpg',
	'http://i.imgur.com/8D9YRYW.jpg',
	'http://i.imgur.com/Ugr7dMy.jpg',
	'http://i.imgur.com/Of9doZV.jpg',
	'http://i.imgur.com/2y1fCYU.jpg',
	'http://i.imgur.com/6yfcpiR.jpg',
	'http://i.imgur.com/bm8W9XA.jpg',
	'http://i.imgur.com/B7dRhwC.jpg',
	'http://i.imgur.com/9sOpbeE.jpg',
	'http://i.imgur.com/xtNQxZ8.jpg',
	'http://i.imgur.com/uth8MpW.jpg',
	'http://i.imgur.com/FOGIUu0.jpg',
	'http://i.imgur.com/Ks2HTCM.jpg',
	'http://i.imgur.com/kyM85Pm.jpg',
	'http://i.imgur.com/0WDki5Q.jpg',
	'http://i.imgur.com/T2VZ48F.jpg',
	'http://i.imgur.com/VbGbTDN.jpg',
	'http://i.imgur.com/VxT42SO.jpg',
	'http://i.imgur.com/ZMcSKql.jpg',
	'http://i.imgur.com/vgrOoEM.jpg',
	'http://i.imgur.com/pZnqfFs.jpg',
	'http://i.imgur.com/gN44DDj.jpg',
	'http://i.imgur.com/wyrLiIr.jpg',
	'http://i.imgur.com/O80w3zR.jpg',
	'http://i.imgur.com/5WARMSM.jpg',
	'http://i.imgur.com/fu6gyio.jpg',
	'http://i.imgur.com/HSUrA9p.jpg',
	'http://i.imgur.com/qvgC6Xb.jpg',
	'http://i.imgur.com/6bxcE5N.jpg',
	'http://i.imgur.com/9xqKs59.jpg',
	'http://i.imgur.com/lmoZW6z.jpg',
	'http://i.imgur.com/oDGPPvB.jpg',
	'http://i.imgur.com/MBS8CAs.jpg',
	'http://i.imgur.com/dYxQwww.jpg',
	'http://i.imgur.com/JU0X6ZU.jpg',
	'http://i.imgur.com/gPZPnRq.jpg',
	'http://i.imgur.com/PmAVyNE.jpg',
	'http://i.imgur.com/x2cXzOu.jpg',
	'http://i.imgur.com/NalODOb.jpg',
	'http://i.imgur.com/BtYMeA0.jpg',
	'http://i.imgur.com/CfuWhTL.jpg',
	'http://i.imgur.com/6etspYS.jpg',
	'http://i.imgur.com/X9RA9uU.jpg',
	'http://i.imgur.com/fTOju5m.jpg',
	'http://i.imgur.com/wvAc9hh.jpg',
	'http://i.imgur.com/ROD6PAX.jpg',
	'http://i.imgur.com/gH53vvU.jpg',
	'http://i.imgur.com/rVRgInz.jpg',
	'http://i.imgur.com/RChFwdg.jpg',
	'http://i.imgur.com/OTbIJiE.jpg',
	'http://i.imgur.com/K6vI7Rr.jpg',
	'http://i.imgur.com/coLIx8L.jpg',
	'http://i.imgur.com/c1d0dqJ.jpg',
	'http://i.imgur.com/fDMQobD.jpg',
	'http://i.imgur.com/Oq3a415.jpg',
	'http://i.imgur.com/eUfViyw.jpg',
	'http://i.imgur.com/miveZ80.jpg',
	'http://i.imgur.com/at1qN3f.jpg',
	'http://i.imgur.com/0cFw2O8.jpg'
];
